---
- name: Copy configuration file
  template:
    src: "{{ coredns_config_file }}"
    dest: "{{ coredns_homedir }}/Corefile"
    owner: root
    group: root
    mode: 0644
  notify: restart coredns

- name: Copy zone files
  template:
    src: "{{ item }}"
    dest: "{{ coredns_homedir }}/zones"
    owner: root
    group: root
    mode: 0644
  with_fileglob: "{{ coredns_zone_files_paths }}"
